version: '3'
services:
  phone-book:
    build: .
    image: phone-book
    user: root
    depends_on:
      - cache
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/PhoneBook
    container_name: phone-book

  cache:
    image: redis
    user: root
    restart: always
    command: redis-server --requirepass rise --maxmemory 100mb --maxmemory-policy allkeys-lru
    ports:
      - 6379:6379
    volumes:
      - cache:/data
    container_name: redis

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    environment:
      - REDIS_URI=redis://redis:6379
    container_name: redisinsight

volumes:
  cache:
    driver: local
