version: '3'
services:
  phone-book:
    build: .
    image: phone-book
    user: root
    depends_on:
      - cache
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/PhoneBook
    environment:
      POSTGRES_USER: rise
      POSTGRES_PASSWORD: ing_up
      POSTGRES_DB: contacts
    container_name: phone-book

  postgres:
    image: postgres:latest
    restart: always
    user: root
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: rise
      POSTGRES_PASSWORD: ing_up
      POSTGRES_DB: contacts
    volumes:
      - ./data/db:/var/lib/postgresql/data

  cache:
    image: redis
    user: root
    restart: always
    command: redis-server --requirepass rise --maxmemory 100mb --maxmemory-policy allkeys-lru
    ports:
      - 6379:6379
    volumes:
      - cache:/data
    container_name: redis

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    environment:
      - REDIS_URI=redis://redis:6379
    container_name: redisinsight

volumes:
  cache:
    driver: local
